export const breedDetailsBatch10 = [
  {
    id: 181,
    name: "Whippet",
    size: "middelgroot" as const,
    energy: "middelmatig" as const,
    coatCare: "minimaal" as const,
    experience: "beginner" as const,
    goodWithKids: true,
    description: "De Whippet is een elegante, atletische windhond die bekend staat om zijn zachte karakter en snelheid. Deze middelgrote hond combineert gratie met vriendelijkheid en is een uitstekende gezinshond. Whippets zijn kalm binnenshuis maar kunnen buiten explosief rennen. Ze zijn gevoelig, aanhankelijk en passen zich goed aan aan verschillende woonsituaties.",
    traits: ["Snel en atletisch", "Zachtaardig karakter", "Kalm binnenshuis", "Weinig verzorging", "Gevoelig en aanhankelijk"]
  },
  {
    id: 182,
    name: "Greyhound",
    size: "groot" as const,
    energy: "middelmatig" as const,
    coatCare: "minimaal" as const,
    experience: "beginner" as const,
    goodWithKids: true,
    description: "De Greyhound is de snelste hond ter wereld en tegelijk een verrassend rustige huisgenoot. Deze elegante windhond staat bekend als 'de 60 km/u bankzitter' vanwege zijn liefde voor comfort en rust. Greyhounds zijn zachtaardig, geduldig en vaak terughoudend. Ze vereisen minimale verzorging en passen zich goed aan aan appartementleven, mits ze dagelijks kunnen rennen.",
    traits: ["Snelste hondenras", "Rustig en zachtaardig", "Minimale verzorging", "Goed met kinderen", "Houdt van comfort"]
  },
  {
    id: 183,
    name: "Saluki",
    size: "groot" as const,
    energy: "middelmatig" as const,
    coatCare: "gemiddeld" as const,
    experience: "gemiddeld" as const,
    goodWithKids: true,
    description: "De Saluki is een van de oudste hondenrassen, afkomstig uit het Midden-Oosten. Deze elegante windhond combineert gratie met een onafhankelijke persoonlijkheid. Saluki's zijn gereserveerd, waardig en soms afstandelijk, maar vormen diepe banden met hun familie. Ze zijn intelligent maar kunnen eigenzinnig zijn, wat geduld en respect vereist. Hun veerkleed vereist regelmatige verzorging.",
    traits: ["Oude afkomst", "Elegant en waardig", "Onafhankelijk karakter", "Snelle springer", "Gereserveerd maar loyaal"]
  },
  {
    id: 184,
    name: "Afghaanse Windhond",
    size: "groot" as const,
    energy: "middelmatig" as const,
    coatCare: "intensief" as const,
    experience: "ervaren" as const,
    goodWithKids: false,
    description: "De Afghaanse Windhond is een opvallend ras met een luxueuze, zijdeachtige vacht. Deze aristocratische windhond combineert elegantie met een sterk onafhankelijk karakter. Afghanen zijn waardig, gereserveerd en kunnen afstandelijk zijn. Ze zijn intelligent maar eigenwijs, wat consequente training vereist. Hun prachtige vacht vraagt dagelijkse verzorging. Dit ras past bij ervaren eigenaren die hun unieke persoonlijkheid waarderen.",
    traits: ["Luxueuze vacht", "Onafhankelijk en waardig", "Intensieve verzorging", "Elegant en atletisch", "Gereserveerd karakter"]
  },
  {
    id: 185,
    name: "Irish Wolfhound",
    size: "reus" as const,
    energy: "middelmatig" as const,
    coatCare: "gemiddeld" as const,
    experience: "gemiddeld" as const,
    goodWithKids: true,
    description: "De Irish Wolfhound is een van de grootste hondenrassen ter wereld, maar staat bekend als een 'zachte reus'. Deze indrukwekkende windhond combineert imposante grootte met een vriendelijk, rustig karakter. Irish Wolfhounds zijn geduldig, zachtaardig en uitstekend met kinderen. Ze vereisen voldoende ruimte en matige beweging. Hun korte levensverwachting (6-8 jaar) is belangrijk om te overwegen.",
    traits: ["Grootste hondenras", "Zachte reus", "Vriendelijk en geduldig", "Goed met kinderen", "Rustig karakter"]
  },
  {
    id: 186,
    name: "Schotse Deerhound",
    size: "reus" as const,
    energy: "middelmatig" as const,
    coatCare: "gemiddeld" as const,
    experience: "gemiddeld" as const,
    goodWithKids: true,
    description: "De Schotse Deerhound is een nobele, grote windhond met een ruw, grijs gekleurde vacht. Oorspronkelijk gefokt voor hertenjacht, zijn deze honden zachtaardig en vriendelijk. Deerhounds zijn kalm binnenshuis maar genieten van regelmatige gelegenheid om te rennen. Ze zijn geduldig met kinderen en hebben een waardig, rustig karakter. Hun grootte vereist voldoende ruimte en zijn geschikt voor ervaren hondenbezitters.",
    traits: ["Nobele verschijning", "Zachte reus", "Ruwe grijze vacht", "Rustig en waardig", "Goed met gezinnen"]
  },
  {
    id: 187,
    name: "Borzoi",
    size: "reus" as const,
    energy: "middelmatig" as const,
    coatCare: "intensief" as const,
    experience: "ervaren" as const,
    goodWithKids: false,
    description: "De Borzoi (Russische Windhond) is een aristocratische, elegante windhond met een zijdeachtige vacht. Deze Russische honden combineren gratie met een onafhankelijk, gereserveerd karakter. Borzois zijn rustig en waardig binnenshuis maar kunnen explosief rennen. Ze zijn gevoelig en vereisen zachte, positieve training. Hun lange vacht vraagt regelmatige verzorging. Dit ras past bij rustige huishoudens die hun verfijnde karakter waarderen.",
    traits: ["Russische aristocraat", "Elegante verschijning", "Onafhankelijk karakter", "Intensieve vachtverzorging", "Gevoelig en waardig"]
  },
  {
    id: 188,
    name: "Azawakh",
    size: "groot" as const,
    energy: "hoog" as const,
    coatCare: "minimaal" as const,
    experience: "ervaren" as const,
    goodWithKids: false,
    description: "De Azawakh is een slanke, elegante windhond afkomstig uit West-Afrika. Dit ras is extreem atletisch en heeft een uitgesproken jachtinstinct. Azawakhs zijn gereserveerd, onafhankelijk en kunnen territoriaal zijn. Ze vormen sterke banden met hun familie maar zijn vaak afstandelijk naar vreemden. Dit ras vereist ervaring, consequente socialisatie en veel beweging. Hun korte vacht vraagt minimale verzorging.",
    traits: ["Afrikaanse windhond", "Extreem atletisch", "Gereserveerd karakter", "Territoriaal", "Minimale verzorging"]
  },
  {
    id: 189,
    name: "Sloughi",
    size: "groot" as const,
    energy: "middelmatig" as const,
    coatCare: "minimaal" as const,
    experience: "ervaren" as const,
    goodWithKids: false,
    description: "De Sloughi is een elegante Noord-Afrikaanse windhond die bekend staat om zijn waardigheid en reserve. Deze honden zijn gevoelig, intelligent en vormen diepe banden met hun familie, maar blijven vaak afstandelijk naar vreemden. Sloughis zijn rustig binnenshuis maar hebben regelmatig de mogelijkheid nodig om te rennen. Ze vereisen zachte, respectvolle training en vroege socialisatie.",
    traits: ["Noord-Afrikaanse windhond", "Waardig en gereserveerd", "Gevoelig karakter", "Loyaal aan familie", "Minimale verzorging"]
  },
  {
    id: 190,
    name: "Chart Polski",
    size: "groot" as const,
    energy: "middelmatig" as const,
    coatCare: "minimaal" as const,
    experience: "ervaren" as const,
    goodWithKids: true,
    description: "De Chart Polski (Poolse Windhond) is een krachtige, atletische windhond met een zelfverzekerd karakter. Dit zeldzame ras is minder bekend maar combineert jachtcapaciteiten met een rustig huiselijk karakter. Chart Polski's zijn intelligent, onafhankelijk en loyaal aan hun familie. Ze vereisen ervaring en consequente training. Buitenshuis zijn ze snelle renners met een sterk zichtsysteem.",
    traits: ["Poolse windhond", "Krachtig en atletisch", "Zelfverzekerd karakter", "Loyaal aan familie", "Zeldzaam ras"]
  },
  {
    id: 191,
    name: "Galgo Español",
    size: "groot" as const,
    energy: "middelmatig" as const,
    coatCare: "minimaal" as const,
    experience: "beginner" as const,
    goodWithKids: true,
    description: "De Galgo Español (Spaanse Windhond) is een elegante, zachtaardige hond die vaak wordt gered uit Spanje. Deze windhonden zijn rustig, geduldig en vormen diepe banden met hun redders. Galgo's zijn kalm binnenshuis en passen zich goed aan aan gezinslevens. Ze zijn gevoelig en reageren het best op positieve training. Veel Galgo's zijn beschikbaar via rescue organisaties en maken geweldige huisdieren.",
    traits: ["Spaanse windhond", "Zachtaardig karakter", "Rustig binnenshuis", "Gevoelig en loyaal", "Vaak via rescue"]
  },
  {
    id: 192,
    name: "English Foxhound",
    size: "groot" as const,
    energy: "hoog" as const,
    coatCare: "minimaal" as const,
    experience: "ervaren" as const,
    goodWithKids: true,
    description: "De English Foxhound is een traditionele Britse jachthond die is gefokt om in roedels te werken. Deze honden zijn energiek, vriendelijk en sociaal met andere honden. Foxhounds hebben een uitstekend uithoudingsvermogen en vereisen veel beweging. Ze kunnen eigenzinnig zijn en hebben een sterke neus die hen kan afleiden. Dit ras past het best bij actieve eigenaren met ruimte en ervaring met geurbonden.",
    traits: ["Traditionele jachthond", "Hoge energie", "Sociaal met honden", "Eigenzinnig", "Uitstekend uithoudingsvermogen"]
  },
  {
    id: 193,
    name: "American Foxhound",
    size: "groot" as const,
    energy: "hoog" as const,
    coatCare: "minimaal" as const,
    experience: "ervaren" as const,
    goodWithKids: true,
    description: "De American Foxhound is een athletische, onafhankelijke jachthond die lichter gebouwd is dan zijn Engelse neef. Deze honden zijn vriendelijk, energiek en hebben een sterke jachtdrift. American Foxhounds zijn vocaal en kunnen luid huilen. Ze vereisen veel beweging en mentale stimulatie. Hun onafhankelijke karakter kan training uitdagend maken. Dit ras past bij zeer actieve eigenaren met ervaring.",
    traits: ["Amerikaanse jachthond", "Onafhankelijk karakter", "Hoge energie", "Vocaal", "Sterk jachtinstinct"]
  },
  {
    id: 194,
    name: "Beagle-Harrier",
    size: "middelgroot" as const,
    energy: "hoog" as const,
    coatCare: "minimaal" as const,
    experience: "gemiddeld" as const,
    goodWithKids: true,
    description: "De Beagle-Harrier is een Franse geurbonde die groter is dan een Beagle maar kleiner dan een Harrier. Deze vriendelijke honden zijn energiek, sociaal en uitstekend met kinderen. Ze hebben een sterk reukvermogen en kunnen eigenzinnig zijn tijdens wandelingen. Beagle-Harriers zijn vrolijk, vocaal en genieten van gezelschap. Ze vereisen dagelijkse beweging en gedijen bij actieve gezinnen.",
    traits: ["Franse geurbonde", "Vriendelijk en energiek", "Uitstekend met kinderen", "Vocaal", "Sociaal karakter"]
  },
  {
    id: 195,
    name: "Grand Basset Griffon Vendeen",
    size: "groot" as const,
    energy: "hoog" as const,
    coatCare: "gemiddeld" as const,
    experience: "gemiddeld" as const,
    goodWithKids: true,
    description: "De Grand Basset Griffon Vendeen (GBGV) is een Franse geurbonde met een ruwe, shaggy vacht en een vrolijk karakter. Deze honden zijn energiek, vriendelijk en onafhankelijk. GBGV's zijn vocaal en hebben een uitstekend reukvermogen. Ze zijn sociaal met mensen en honden maar kunnen eigenzinnig zijn. Hun vacht vereist regelmatig borstelen. Dit ras past bij actieve gezinnen die hun vrolijke, soms eigenwijze karakter waarderen.",
    traits: ["Franse geurbonde", "Ruwe shaggy vacht", "Vrolijk en energiek", "Vocaal", "Onafhankelijk"]
  },
  {
    id: 196,
    name: "Petit Basset Griffon Vendeen",
    size: "klein" as const,
    energy: "hoog" as const,
    coatCare: "gemiddeld" as const,
    experience: "gemiddeld" as const,
    goodWithKids: true,
    description: "De Petit Basset Griffon Vendeen (PBGV) is een kleine, levendige Franse geurbonde met een charmant, ruw uiterlijk. Deze 'happy breed' is energiek, vriendelijk en heeft een grote persoonlijkheid in een klein lichaam. PBGV's zijn eigenzinnig, vocaal en uitstekend met kinderen. Ze vereisen dagelijkse beweging en mentale stimulatie. Hun ruwe vacht vraagt regelmatig borstelen.",
    traits: ["Kleine geurbonde", "Levendig en vrolijk", "Grote persoonlijkheid", "Eigenzinnig", "Uitstekend met kinderen"]
  },
  {
    id: 197,
    name: "Bloodhound",
    size: "reus" as const,
    energy: "middelmatig" as const,
    coatCare: "gemiddeld" as const,
    experience: "gemiddeld" as const,
    goodWithKids: true,
    description: "De Bloodhound heeft het beste reukvermogen van alle hondenrassen en wordt wereldwijd ingezet voor opsporingswerk. Deze grote, zachtaardige honden zijn vriendelijk, geduldig en uitstekend met kinderen. Bloodhounds zijn eigenzinnig en worden volledig geleid door hun neus. Ze kwijlen veel en vereisen ruimte. Hun zachte karakter en loyaliteit maken ze geliefde gezinshonden voor wie hun eigenaardigheden kan waarderen.",
    traits: ["Beste reukvermogen", "Zachtaardig karakter", "Eigenzinnig", "Kwijlt veel", "Uitstekend met kinderen"]
  },
  {
    id: 198,
    name: "Otterhound",
    size: "groot" as const,
    energy: "hoog" as const,
    coatCare: "intensief" as const,
    experience: "gemiddeld" as const,
    goodWithKids: true,
    description: "De Otterhound is een zeldzaam, groot ras met een ruwe, waterbestendige vacht en zwemvliezen tussen de tenen. Oorspronkelijk gefokt voor otterjacht, zijn deze honden vriendelijk, energiek en dol op water. Otterhounds zijn vocaal, sociaal en hebben een vrolijk karakter. Ze vereisen veel beweging en hun dikke vacht vraagt intensieve verzorging. Dit bijzondere ras past bij actieve gezinnen met ruimte.",
    traits: ["Zeldzaam ras", "Dol op water", "Ruwe waterbestendige vacht", "Vriendelijk en vocaal", "Zwemvliezen"]
  },
  {
    id: 199,
    name: "Black and Tan Coonhound",
    size: "groot" as const,
    energy: "hoog" as const,
    coatCare: "minimaal" as const,
    experience: "gemiddeld" as const,
    goodWithKids: true,
    description: "De Black and Tan Coonhound is een Amerikaanse geurbonde met een opvallende zwart-bruine vacht. Deze vriendelijke honden zijn energiek, ontspannen en uitstekend met kinderen. Coonhounds zijn extreem vocaal met een kenmerkende 'bay' en hebben een sterk jachtinstinct. Ze zijn sociaal, geduldig en passen zich goed aan aan gezinslevens. Regelmatige beweging en veilige omheiningen zijn essentieel.",
    traits: ["Amerikaanse geurbonde", "Vriendelijk karakter", "Extreem vocaal", "Goed met kinderen", "Minimale verzorging"]
  },
  {
    id: 200,
    name: "Bluetick Coonhound",
    size: "groot" as const,
    energy: "hoog" as const,
    coatCare: "minimaal" as const,
    experience: "gemiddeld" as const,
    goodWithKids: true,
    description: "De Bluetick Coonhound is een atletische Amerikaanse geurbonde met een opvallend gespikkeld blauw patroon. Deze honden zijn vriendelijk, intelligent en energiek. Blueticks zijn vocaal, hebben een sterk jachtinstinct en uitstekend uithoudingsvermogen. Ze zijn geduldig met kinderen en sociaal met andere honden. Dit ras vereist veel beweging en mentale stimulatie, en past bij actieve buitenmensen.",
    traits: ["Opvallende spikkelvacht", "Atletisch en energiek", "Zeer vocaal", "Vriendelijk karakter", "Uitstekend uithoudingsvermogen"]
  },
  {
    id: 201,
    name: "Redbone Coonhound",
    size: "groot" as const,
    energy: "hoog" as const,
    coatCare: "minimaal" as const,
    experience: "gemiddeld" as const,
    goodWithKids: true,
    description: "De Redbone Coonhound is een atletische Amerikaanse geurbonde met een prachtige mahonie-rode vacht. Deze honden zijn vriendelijk, even-tempered en uitstekend met kinderen. Redbones zijn energiek, vocaal en hebben een sterk jachtinstinct. Ze zijn socialer en minder eigenzinnig dan sommige andere coonhounds. Dit ras vereist veel beweging en past bij actieve gezinnen die hun vrolijke, loyale karakter waarderen.",
    traits: ["Mahonie-rode vacht", "Vriendelijk en even-tempered", "Energiek en vocaal", "Uitstekend met kinderen", "Sociaal karakter"]
  },
  {
    id: 202,
    name: "Plott Hound",
    size: "groot" as const,
    energy: "hoog" as const,
    coatCare: "minimaal" as const,
    experience: "ervaren" as const,
    goodWithKids: true,
    description: "De Plott Hound is de staatshond van North Carolina en verschilt van andere coonhounds door zijn Duitse afkomst. Deze moedige honden zijn intelligent, loyaal en hebben een sterk beschermend instinct. Plotts zijn energiek, vocaal en oorspronkelijk gefokt voor berenjacht. Ze zijn vriendelijk met familie maar kunnen gereserveerd zijn naar vreemden. Dit ras vereist ervaring, consequente training en veel beweging.",
    traits: ["Staatshond North Carolina", "Moedig en loyaal", "Beschermend instinct", "Hoge energie", "Vereist ervaring"]
  }
];
